# Generated by Django 4.2 on 2024-07-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_avatar_alter_person_email_alter_person_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='md5',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
