# Generated by Django 4.2 on 2024-07-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_avatar_md5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
