# Generated by Django 4.2 on 2024-07-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_person_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='avatar',
        ),
    ]
