# Generated by Django 4.2 on 2024-08-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, to='myadmin.groups')),
                ('permissions', models.ManyToManyField(blank=True, to='myadmin.permissions')),
            ],
        ),
        migrations.AddField(
            model_name='groups',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='myadmin.permissions'),
        ),
    ]
