# Generated by Django 4.2 on 2024-08-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_alter_myadmin_options_alter_myadmin_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myadmin',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='myadmin',
            name='is_authenticated',
        ),
    ]
